version: '3.8'

services:
  rbh-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"  # Expose port directly for container access
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${DATASOURCE_DB_NAME}
      MYSQL_USER: ${DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

networks:
  my-network: